# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: carro.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Carro(betterproto.Message):
    modelo: str = betterproto.string_field(1)
    cor: str = betterproto.string_field(2)


@dataclass
class Motor(betterproto.Message):
    marcha: int = betterproto.int32_field(1)
    velocidade: str = betterproto.string_field(2)
    ligado: bool = betterproto.bool_field(3)


@dataclass
class Pneu(betterproto.Message):
    rotacao: int = betterproto.int32_field(1)
